# Phone webcam configuration file
# Copy to config.conf and modify as needed

# Virtual camera device (should match v4l2loopback video_nr)
VIDEO_NR="10"

# front-1 and back-0
CAMERA_ID="1"

# Resolution: 1920*1080, 1280*720, 640*480
# Lower resolution gives lower latency
RES="1280x720"

# Limits the Size, improves performance
MAX_SIZE="1280"

# Limits the bit rate, improves performance
BIT_RATE="4M"

# CODEC
CODEC="h264"

# MAX FRAME RATE
MAX_FPS="30"

# VIDEO BUFFER (delays the video feed)
VIDEO_BUFFER="0"

# NO AUDIO FEED, this stop capturing sound, improves performance.
NO_AUDIO="true"

# TURN OFF AUDIO FROM PLAYING, false--OFF and true--ON
AUDIO_PLAY_BACK="false"

# Set to true to show a preview window (useful for debugging)
SHOW_PREVIEW="true"

# makes the window always top of other windows
ALWAYS_ON_TOP="true"

# Name shown in applications
CARD_LABEL="Android webcam"
